
name: Build Raspberry Pi Pico Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: |
        sudo apt update
        sudo apt install -y cmake gcc-arm-none-eabi build-essential libnewlib-arm-none-eabi git

    - name: Clonar o SDK do Pico
      run: |
        git clone -b master https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init
        cd ..
        echo "PICO_SDK_PATH=$PWD/pico-sdk" >> $GITHUB_ENV

    - name: Criar diretório de build
      run: mkdir build

    - name: Compilar o projeto
      run: |
        cd build
        cmake .. -DPICO_SDK_PATH=$PICO_SDK_PATH
        make

    - name: Upload dos binários compilados
      uses: actions/upload-artifact@v4
      with:
        name: binarios-rain-monitor
        path: |
          build/*.uf2
          build/*.bin
          build/*.elf
